version: 1.0.{build}-{branch}

image: Visual Studio 2017

branches:
  # blacklist
  except:
    - gh-pages
 
artifacts:
  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: bin\Debug\
    name: Diashow_Debug
  - path: bin\Release\
    name: Diashow_Release

before_build:
  - nuget restore
